### ISSUE TITLE
Issue with loopOut() in dotlottie-player-light

### ISSUE THREAD

**Issue by Rapsssito** [aarsteinmedia/dotlottie-player#3]
First of all, thanks a lot for the package. It works great!

I would like to point out an issue with `dotlottie-player-light`. I am testing the same animation with both `dotlottie-player-light` and `dottie-player`. [Animation link](https://adelantevalladolid.es/wp-content/uploads/2023/11/hero-web.lottie).

With `dotlottie-player` it works flawlessly. However, when running the animation with `dotlottie-player-light`, some parts do not work. In my case, the "bike" animation at the end (which was created using the `loopOut()` command in AE), does not loop.

**Comment by johanaarstein** [comment]
Thanks! I'll look into it.

**Comment by johanaarstein** [comment]
Hi again! Sorry for the late answer. LoopOut is one of the features that has been left out of the light version to make it as terse as possible. I'm afraid you either need to use another method to get your animation to work, or just use the full version. 😇

**Comment by Rapsssito** [comment]
Thanks! That's a shame... I really like `loopOut()`.
